name: 部署

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: src